name: nwbPipeline
channels:
  - pennmem
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - ptsa=3.0.5  # this package has import (and perhaps installing) error, TimeSeries works
  - pip
  - pip:
      - poetry
